robot_radius: 0.16495
transform_tolerance: 0.5

obstacles_layer:
  observation_sources: bumper_pointcloud

  bumper_pointcloud:
    sensor_frame: base_link
    data_type: PointCloud2
    topic: /bumper/pointcloud
    marking: true
    clearing: true
    obstacle_range: 2.5
    raytrace_range: 3.0

inflation_layer:
  inflation_radius: 0.2
  cost_scaling_factor: 12
